### ISSUE TITLE
Add Ontology / CV support

### ISSUE THREAD

**Issue by torogi94** [JR-1991/software-driven-rdm#19]
As discussed, the following would be required to support CVs:
- a register of CVs that have been used, with
  - name of the CV
  - version
  - URI
- the ability to sign an object or field with one of the above CVs, using
  - parent CV from register
  - name of the term
  - accession of the term (ABC:XXXXXXXX)

**Comment by JR-1991** [comment]
I can imagine that it would make sense to employ this functionality similar to incorporating sub-models via a GitHub link to add external CVs. Something like this within the markdown:

> ### SomeObject
>
> - ontology
>    - Type: https://github.com/EBI-BioModels/SBO.git

One thing though is that there needs to be some kind of validation that this in fact is an ontology. Maybe check if an `owl`or `obo` file is present, if a repo is given. In the case of a non-repo ontology a direct link to the same files would make sense. Following this route we could start by trying to parse an `owl` file and extract the terms to the sdRDM `Enumeration` class.

We should also think about how we can employ the `nmrML` way of referencing a CV within the serialized format such that is reproducible. As pointed out in our meeting, it can be structured similar to the `__source__` part which holds the commit hash with which this dataset has been created. I could think of something like this in the case of YAML serialization:

```yaml
someObject:
  ontology:
    value: SBO:00000
    cv: "#SBOTerms"
__ontologies__:
  SBOTerms:
    ref: https://github.com/EBI-BioModels/SBO.git
    commit: 83a9081
__source__:
  repo: "... the usual stuff you'd find here"
```

What are your thoughts?
